title: cpfct.org
logo: CPF_logo.png
description: Citizens Policy Forum of Connecticut, Inc is a 501(c)(3) organization.
# show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
